language: node_js
cache:
  directories:
  - ~/.npm
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- npm run lint
- npm run test
- commitlint-travis
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
